version: '3.7'

services:
  api:
   container_name: assetlinetrade_api
   image: s4g3/assetline-api
   build:
     context: .
     target: production
     dockerfile: ./Dockerfile
   restart: unless-stopped
   ports:
     - 1313:1313
     - 80:80
   environment:
      VIRTUAL_HOST: coinjettrade.com,www.coinjettrade.com
      VIRTUAL_PORT: 1313
      LETSENCRYPT_HOST: coinjettrade.com,www.coinjettrade.com
      LETSENCRYPT_EMAIL: dthc@protonmail.com
   command: npm run start:prod

networks:
    default:
        external:
            name: nginx-proxy
